apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}  
  name: mongodb-configmap-init
data:
  on-start.sh: |
{{ .Files.Get "init/on-start.sh" | indent 4 }}